INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(101,"TCS",2000.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(12,"INFOSYS",3000.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(13,"HCL",4000.00);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(11,"SBI",6000.00);